# Generated by Django 4.2.1 on 2023-05-06 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorcycle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', ''), ('NAKED', 'Naked'), ('SPORT', 'Sport'), ('TOURING', 'Touring'), ('OFF-ROAD', 'Off-road'), ('SCOOTER', 'Scooter'), ('MOTONETA', 'Motoneta'), ('CUSTOM', 'Custom'), ('STREET', 'Street'), ('BIGTRAIL', 'Big Trail'), ('CUSTOM', 'Custom'), ('STREET', 'Street')], default=None, max_length=20, null=True)),
                ('origin', models.CharField(choices=[('', ''), ('NACIONAL', 'Nacional'), ('IMPORTADA', 'Importada')], default=None, max_length=10, null=True)),
                ('fabrication_year', models.PositiveSmallIntegerField()),
                ('model_year', models.PositiveSmallIntegerField()),
                ('license_plate', models.CharField(max_length=20)),
                ('mileage', models.PositiveIntegerField(default=None, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('color', models.CharField(choices=[('', ''), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('VERMELHO', 'Vermelho'), ('PRETO', 'Preto'), ('BRANCO', 'Branco')], default=None, max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_phrase', models.CharField(default=None, max_length=500, null=True)),
                ('description', models.TextField(default=None, max_length=4000, null=True)),
                ('optional_alarm', models.BooleanField(default=False)),
                ('optional_chest', models.BooleanField(default=False)),
                ('optional_computer', models.BooleanField(default=False)),
                ('optional_gps', models.BooleanField(default=False)),
                ('accept_new_offer', models.BooleanField(default=False)),
                ('accept_exchange', models.BooleanField(default=False)),
                ('doc_ok', models.BooleanField(default=None, null=True)),
                ('track_ready', models.BooleanField(default=None, null=True)),
                ('brake_system', models.CharField(choices=[('', ''), ('ABS', 'ABS'), ('TAMBOR', 'Tambor'), ('COMBINADO', 'Combinado')], default=None, max_length=10, null=True)),
                ('ignition_system', models.CharField(choices=[('', ''), ('PEDAL', 'Pedal'), ('ELETRICA', 'Elétrica'), ('AMBOS', 'Ambos')], default=None, max_length=10, null=True)),
                ('refrigeration', models.CharField(choices=[('', ''), ('AR', 'Ar'), ('LIQUIDA', 'Líquida')], default=None, max_length=10, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('PUBLISHED', 'Publicado'), ('DELETE', 'Excluir'), ('EXPIRED', 'Expirado'), ('INACTIVE', 'Inativo'), ('UPDATE', 'Atualizar')], default='NEW', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycle.motorcyclebrandmodel')),
                ('model_version', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='motorcycle.motorcyclemodelversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classifiedad',
            },
        ),
        migrations.CreateModel(
            name='ClassifiedAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('classifiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifiedad.classifiedad')),
            ],
            options={
                'db_table': 'classifiedad_images',
            },
        ),
    ]
