# Generated by Django 4.2.1 on 2023-07-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userprofile_authz_sms_userprofile_authz_whatsapp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
