apiVersion: batch/v1
kind: Job
metadata:
  name: motando-app-init
spec:
  template:
    spec:
      containers:
      - name: appinit-crt
        image: gru.ocir.io/grxmw2a9myyj/motando-webapp-init:v1.0.0
        command: ["/bin/bash",  "./motando-webapp-init.sh"]
        env:
            - name: APP_ENV
              value: "PRD"  
            - name: OCI_REGION_ID
              value: "sa-saopaulo-1"
            - name: OCI_OBJSTR_NAMESPACE
              valueFrom:
                  configMapKeyRef:
                      name: motando-config
                      key: objstr-namespace
            - name: OCI_BUCKET_MOTANDO_IMGTMP
              value: "motando-tmpimg"
            - name: OCI_BUCKET_MOTANDO_IMG
              value: "motando-img"
            - name: OCI_STATICFILES_BUCKET_NAME
              value: "motando-staticfiles"
            - name: OCI_ACCESS_KEY_ID
              valueFrom:
                  secretKeyRef:
                      name: motando-keys
                      key: access-key
            - name: OCI_SECRET_ACCESS_KEY
              valueFrom:
                  secretKeyRef:
                      name: motando-keys
                      key: secret-key                      
            - name: MYSQL_HOST
              valueFrom:
                  secretKeyRef:
                      name: mysql-secret
                      key: host       
            - name: MYSQL_USER
              valueFrom:
                  secretKeyRef:
                      name: mysql-secret
                      key: user       
            - name: MYSQL_PASSWD
              valueFrom:
                  secretKeyRef:
                      name: mysql-secret
                      key: passwd
            - name: MYSQL_DBNAME
              value: "motandodb"
            - name: CLASSIFIEDAD_TASK_QUEUE_HOST
              value: "celery-classifiedad.default.svc.cluster.local"
            - name: CLASSIFIEDAD_TASK_QUEUE_PORT
              value: "8100"
      imagePullSecrets:
          - name: motando-ocir-secret
      restartPolicy: Never
  backoffLimit: 0