# Generated by Django 4.2.1 on 2023-07-18 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifiedad', '0002_alter_classifiedad_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField()),
                ('classifiedad_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classifiedad.classifiedad')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chats_registered_user',
            },
        ),
        migrations.CreateModel(
            name='ChatAnonymousUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from_email', models.EmailField(max_length=254)),
                ('user_from_telephone', models.PositiveSmallIntegerField()),
                ('message', models.JSONField()),
                ('classifiedad_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classifiedad.classifiedad')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chats_anonymous_user',
            },
        ),
    ]
