# Generated by Django 4.2.1 on 2023-07-18 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatanonymoususer',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='chatregistereduser',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='chatanonymoususer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatregistereduser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
