# Generated by Django 4.2.1 on 2023-07-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatanonymoususer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatanonymoususer',
            old_name='classifiedad_id',
            new_name='classifiedad',
        ),
        migrations.RenameField(
            model_name='chatregistereduser',
            old_name='classifiedad_id',
            new_name='classifiedad',
        ),
    ]
