# Generated by Django 4.2.1 on 2023-07-18 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_chat_remove_chatregistereduser_classifiedad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_from_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='user_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
