# Generated by Django 4.2.1 on 2023-07-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_message_chat_messages'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='chats',
        ),
    ]
