# Generated by Django 4.2.1 on 2023-06-09 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_city', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='state_city',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='state_city.statecity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='state_city.state'),
            preserve_default=False,
        ),
    ]
