# Generated by Django 4.2.1 on 2023-06-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle', '0002_rename_motorcyclemodelversion_motorcyclebrandmodelversion_and_more'),
        ('account', '0002_remove_userprofile_state_city_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='complement',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_motorcycle',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='motorcycle_brand_model_wanted',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='motorcycle.motorcyclebrandmodel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='motorcycle_brand_wanted',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='motorcycle.motorcyclebrand'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
