# Generated by Django 4.2.1 on 2023-06-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='complement',
            new_name='address_complement',
        ),
    ]
