# Generated by Django 4.2.1 on 2023-06-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_complement_userprofile_address_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='motorcycle_wanted_year',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
