#
# gru_nosql.tf
#

resource "oci_nosql_table" "nosql_table_chats" {    
    compartment_id = var.root_compartment
    name = "motando_chats"
    ddl_statement = <<EOS
        CREATE TABLE IF NOT EXISTS motando_chats (
           id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
           id_from INTEGER,
           fullname_from STRING,
           email_from STRING,
           telephone_from STRING,           
           id_to INTEGER,
           fullname_to STRING,
           classifiedad_id INTEGER,
           message STRING,           
           date_created TIMESTAMP(0),           
        PRIMARY KEY(id)) USING TTL 15 days
    EOS

    table_limits {
        max_read_units = 1
        max_write_units = 1
        max_storage_in_gbs = 1
    }
}