# Generated by Django 4.2.1 on 2023-06-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userprofile_motorcycle_wanted_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscribe_offer',
            field=models.BooleanField(default=False),
        ),
    ]
