# Generated by Django 4.2.4 on 2023-08-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='motorcycle_wanted_year',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
