# Generated by Django 4.2.4 on 2023-08-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
