# Generated by Django 4.2.1 on 2023-07-08 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle', '0002_rename_motorcyclemodelversion_motorcyclebrandmodelversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifiedad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='motorcycle.motorcyclebrandmodel'),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='model_version',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='motorcycle.motorcyclebrandmodelversion'),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
