# Generated by Django 4.2.4 on 2023-08-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiedad', '0002_alter_classifiedad_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='brake_system',
            field=models.CharField(choices=[('', ''), ('abs', 'ABS'), ('tambor', 'Tambor'), ('combined', 'Combinado')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='color',
            field=models.CharField(choices=[('', ''), ('blue', 'Azul'), ('green', 'Verde'), ('red', 'Vermelho'), ('black', 'Preto'), ('white', 'Branco'), ('silver', 'Prata'), ('yellow', 'Amarelo'), ('purple', 'Roxo')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='ignition_system',
            field=models.CharField(choices=[('', ''), ('pedal', 'Pedal'), ('electric', 'Elétrica'), ('both', 'Ambos')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='origin',
            field=models.CharField(choices=[('', ''), ('national', 'Nacional'), ('imported', 'Importada')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='refrigeration',
            field=models.CharField(choices=[('', ''), ('air', 'Ar'), ('liquid', 'Líquida')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('publised', 'Publicado'), ('delete', 'Excluir'), ('expired', 'Expirado'), ('inactive', 'Inativo'), ('update', 'Atualizar')], default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='type',
            field=models.CharField(choices=[('', ''), ('naked', 'Naked'), ('sport', 'Sport'), ('touring', 'Touring'), ('offroad', 'Off-road'), ('scooter', 'Scooter'), ('motoneta', 'Motoneta'), ('custom', 'Custom'), ('street', 'Street'), ('bigtrail', 'Big Trail')], default=None, max_length=20, null=True),
        ),
    ]
