# Generated by Django 4.2.4 on 2023-08-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiedad', '0003_alter_classifiedad_brake_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('publised', 'Publicado'), ('delete', 'Excluir'), ('expired', 'Expirado'), ('inactive', 'Inativo'), ('update', 'Atualizar')], default='new', max_length=10),
        ),
    ]
