# Generated by Django 4.2.4 on 2023-08-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiedad', '0004_alter_classifiedad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='top_offer',
            field=models.BooleanField(default=False),
        ),
    ]
