apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      name: mgmt-ui
      port: 15672
      targetPort: 15672   
    - protocol: TCP
      name: amqp
      port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: celery-classifiedad
spec:
  type: ClusterIP
  selector:
    app: celery-classifiedad
  ports:
    - protocol: TCP
      name: flower
      port: 5555
      targetPort: 5555
    - protocol: TCP
      name: xmlrpc
      port: 8100
      targetPort: 8100
    