# Generated by Django 4.2.1 on 2023-05-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, unique=True)),
                ('popular', models.BooleanField(default=False)),
                ('image_url', models.URLField(default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'motorcycle_brands',
            },
        ),
        migrations.CreateModel(
            name='MotorcycleBrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('image_url', models.URLField(default=None, max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_models', to='motorcycle.motorcyclebrand')),
            ],
            options={
                'db_table': 'motorcycle_brand_models',
            },
        ),
        migrations.CreateModel(
            name='MotorcycleModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('image_url', models.URLField(default=None, max_length=255, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_versions', to='motorcycle.motorcyclebrandmodel')),
            ],
            options={
                'db_table': 'motorcycle_model_versions',
            },
        ),
    ]
