# Generated by Django 4.2.1 on 2023-07-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_classifiedad_id_chatanonymoususer_classifiedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatanonymoususer',
            name='user_from_telephone',
            field=models.CharField(max_length=40),
        ),
    ]
