# Generated by Django 4.2.1 on 2023-07-18 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifiedad', '0002_alter_classifiedad_model_and_more'),
        ('chat', '0004_alter_chatanonymoususer_user_from_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from_fullname', models.CharField(max_length=200)),
                ('user_from_email', models.EmailField(max_length=254)),
                ('user_from_telephone', models.CharField(max_length=40)),
                ('user_from_id', models.PositiveIntegerField(default=None, null=True)),
                ('message', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('classifiedad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classifiedad.classifiedad')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_chats',
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='chatregistereduser',
            name='classifiedad',
        ),
        migrations.RemoveField(
            model_name='chatregistereduser',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='chatregistereduser',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='ChatAnonymousUser',
        ),
        migrations.DeleteModel(
            name='ChatRegisteredUser',
        ),
    ]
