# Generated by Django 4.2.1 on 2023-07-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chat_user_from_id_chat_user_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_from_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_from_fullname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_from_telephone',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
