apiVersion: v1
kind: Service
metadata:
  name: dramatiq-classifiedad
spec:
  type: ClusterIP
  selector:
    app: dramatiq-classifiedad
  ports:    
    - protocol: TCP
      name: xmlrpc
      port: 8100
      targetPort: 8100
    