apiVersion: apps/v1
kind: Deployment
metadata:
  name: motando-webapp
spec:
  selector:
    matchLabels:
      app: motando-webapp
  replicas: 3
  template:
    metadata:
      labels:
        app: motando-webapp
    spec:      
      containers:
      - name: webapp-crt
        image: gru.ocir.io/grxmw2a9myyj/motando-webapp:v1.0.0
        imagePullPolicy: Always        
        ports:
            - containerPort: 8000
        env:
            - name: APP_ENV
              value: "PRD"
            - name: OCI_REGION_ID
              value: "sa-saopaulo-1"
            - name: OCI_BUCKET_MOTANDO_IMGTMP
              value: "motando-tmpimg"
            - name: OCI_BUCKET_MOTANDO_IMG
              value: "motando-img"
            - name: OCI_STATICFILES_BUCKET_NAME
              value: "motando-staticfiles"
            - name: CLASSIFIEDAD_TASK_QUEUE_HOST
              value: "celery-classifiedad.motando.svc.cluster.local"
            - name: CLASSIFIEDAD_TASK_QUEUE_PORT
              value: "8100"
            - name: MYSQL_DBNAME
              value: "motandodb"
            - name: DJANGO_SECRET_KEY
              valueFrom:
                  secretKeyRef:
                      name: motando-keys
                      key: django-seckey           
            - name: OCI_OBJSTR_NAMESPACE
              valueFrom:
                  configMapKeyRef:
                      name: motando-config
                      key: objstr-namespace            
            - name: OCI_ACCESS_KEY_ID
              valueFrom:
                  secretKeyRef:
                      name: motando-keys
                      key: access-key
            - name: OCI_SECRET_ACCESS_KEY
              valueFrom:
                  secretKeyRef:
                      name: motando-keys
                      key: secret-key              
            - name: MYSQL_HOST
              valueFrom:
                  secretKeyRef:
                      name: mysql-secret
                      key: host       
            - name: MYSQL_USER
              valueFrom:
                  secretKeyRef:
                      name: mysql-secret
                      key: user       
            - name: MYSQL_PASSWD
              valueFrom:
                  secretKeyRef:
                      name: mysql-secret
                      key: passwd            
            - name: WEBAPP_LOG_ID
              valueFrom:
                  configMapKeyRef:
                      name: motando-config
                      key: webapp-log-id          
        livenessProbe:
            httpGet:
                path: /account/login
                port: 8000
            initialDelaySeconds: 5    
            periodSeconds: 5
        resources:
            requests:
                memory: "500Mi"
                cpu: "250m"
            limits:
                memory: "600Mi"
                cpu: "350m"  
      imagePullSecrets:
          - name: motando-ocir-secret