apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  labels:
    app: webapp
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: webapp